workout-tracker/config/routes.rb
WorkoutTracker::Application.routes.draw do

  resources :runs
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root :to => 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

workout-tracker/app/models/run.rb
class Run < ActiveRecord::Base
  attr_accessible :date, :distance, :timeElapsed, :user_id
  belongs_to :user
end

workout-tracker/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  validates :name, presence: true
  has_many :runs
  
  #def initialize(attributes = {})
  #  @name = attributes[:name]
  #  @email = attributes[:email]
  #end
end

workout-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
  # Force signout to prevent CSRF attacks
  #def handle_unverified_request
  #  sign_out
  #  super
  #end
end

workout-tracker/app/controllers/runs_controller.rb
class RunsController < ApplicationController
  # GET /runs
  # GET /runs.json
  def index
    @runs = Run.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @runs }
    end
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
    @run = Run.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @run }
    end
  end

  # GET /runs/new
  # GET /runs/new.json
  def new
    @run = Run.new
    @user_id = params[:user_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @run }
    end
  end

  # GET /runs/1/edit
  def edit
    @run = Run.find(params[:id])
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(params[:run]) 
    
    @run.user_id = self.current_user.id

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render json: @run, status: :created, location: @run }
      else
        format.html { render action: "new" }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /runs/1
  # PUT /runs/1.json
  def update
    @run = Run.find(params[:id])

    respond_to do |format|
      if @run.update_attributes(params[:run])
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run = Run.find(params[:id])
    @run.destroy

    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end
end

workout-tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user
      # Sign in
      puts "found " + user.name
      sign_in user
      redirect_to user
    else
      flash.now[:error] = "Invalid email"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
  
end

workout-tracker/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

workout-tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    
    #Get the last 5 runs the user ran
    @run_feed = Run.where(user_id: params[:id]).order('date DESC').first(5)
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      # success
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to users_url
  end
end

workout-tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

workout-tracker/app/helpers/runs_helper.rb
module RunsHelper
end

workout-tracker/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user] = user.id
    self.current_user = user
  end
  
   def signed_in?
    !self.current_user.nil?
  end
  
  def sign_out
    self.current_user = nil
    session.delete(:user)
  end

  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_id(session[:user])
  end
end

workout-tracker/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

workout-tracker/app/helpers/users_helper.rb
module UsersHelper
 
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

workout-tracker/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Profile",  current_user %></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
          <li><%= link_to "Users", users_path%></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

workout-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class='container'>
  	<% flash.each do |key, value| %>
  	  <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

workout-tracker/app/views/runs/_form.html.erb
<%= form_for(@run) do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  	<%= f.label :Date %>
	<%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :timeElapsed %><br />
    <%= f.number_field :timeElapsed %>
  </div>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
   <%# <%= f.hidden_field :user_id, :value => @user_id %> %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workout-tracker/app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

workout-tracker/app/views/runs/index.html.erb
<h1>Listing runs</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Timeelapsed</th>
    <th>Distance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @runs.each do |run| %>
  <tr>
    <td><%= run.date %></td>
    <td><%= run.timeElapsed %></td>
    <td><%= run.distance %></td>
    <td><%= link_to 'Show', run %></td>
    <td><%= link_to 'Edit', edit_run_path(run) %></td>
    <td><%= link_to 'Destroy', run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Run', new_run_path %>

workout-tracker/app/views/runs/new.html.erb
<h1>New run</h1>

<%= render 'form' %>

<%= link_to 'Back', runs_path %>

workout-tracker/app/views/runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @run.date %>
</p>

<p>
  <b>Timeelapsed:</b>
  <%= @run.timeElapsed %>
</p>

<p>
  <b>Distance:</b>
  <%= @run.distance %>
</p>


<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', runs_path %>

workout-tracker/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

workout-tracker/app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Placeholder home page</h1>

  <h2>
    This is the starting page of the app
  </h2>

</div>

workout-tracker/app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

	  <br>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

workout-tracker/app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user %>
      <%= link_to user.name, user %>
      <% if current_user.admin? %>
     	  | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

workout-tracker/app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

	  <br>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

workout-tracker/app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div id='content' class='container-fluid'>
	<div class='row-fluid'>

		<div class='span4'>
			<p><%= gravatar_for @user %></p>
			<p><%= @user.name %></p>
			<p><%= @user.email %></p>
			<br>
			<p><%= link_to 'Edit Profile', edit_user_path(@user)%></p>
		</div>

		<div class='span8'>

			<%= link_to 'Add Run', new_run_path(:user_id => @user.id), :class => "btn", :id => "btn-add-run" %>
			
			<ul id="recent-runs-list">
				<% @run_feed.each do |run| %>
					<li><%= link_to "On #{run.date} ran #{run.distance} in #{run.timeElapsed}", run_path(run.id), class: "list-group-item" %></li>
				<% end %>
			</ul>
			<%= link_to 'All Runs...', runs_path %>
		</div>	

	</div>
</div>